lsi: false
highlighters: true
permalink: none
baseurl: "https://jagcesar.se"

# Site settings
title: JagCesar
company: Jay C AB
email: cesar@jagcesar.se
description: ""


# Team names, titles and social links
people:
- name: César Pinto Castillo
  pic: cesar
  position: iOS Engineer
  social:
    - title: twitter
      url: https://twitter.com/jagcesar
    - title: github
      url: https://github.com/JagCesar
    - title: linkedin
      url: https://www.linkedin.com/in/jagcesar
    - title: dribbble
      url: https://dribbble.com/JagCesar
- name: Sofia Larsson
  pic: sofia
  position: Illustrator and iOS engineer
  social:
    - title: twitter
      url: https://twitter.com/sclarsson
    - title: instagram
      url: https://instagram.com/fosiadesign

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
