lsi: false
highlighters: true
permalink: none
baseurl: "https://jagcesar.se"

# Site settings
title: JagCesar
email: cesar@jagcesar.se
description: "An experienced iOS Engineer with a passion for creating intuitive user experiences and insanely great products."


# Team names, titles and social links
people:
- name: César Pinto Castillo
  pic: cesar
  position: iOS Engineer, UX Designer & Product Manager
  social:
    - title: twitter
      url: http://twitter.com/jagcesar
    - title: facebook
      url: https://www.facebook.com/JagCesar
    - title: github
      url: http://github.com/JagCesar
    - title: linkedin
      url: https://www.linkedin.com/in/jagcesar
    - title: dribbble
      url: https://dribbble.com/JagCesar

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
